@startuml

title __TERRATALES's Class Diagram__\n

      class org.un.sdgs.terratales.FavoritesController {
          ~ descriptionLabel : Label
          ~ favoritesList : ArrayList<Location>
          ~ favoritesVbox : VBox
          ~ locationImage : ImageView
          ~ nameLabel : Label
          ~ placeLabel : Label
          ~ userLabel : Label
          + onLocationPress()
          + onMapPress()
          + onSignoutPress()
          - changeLocation()
          - createLocationButton()
          - initialize()
          - setDropShadow()
          - setFavoritesList()
      }

      interface org.un.sdgs.terratales.IDatabase {
          {abstract} + load()
      }

      class org.un.sdgs.terratales.LandDatabase {
          {static} - instance : LandDatabase
          - locationList : ArrayList<Location>
          - mapImage : Image
          + LandDatabase()
          {static} + getInstance()
          + getLocationList()
          + getMapImage()
          + load()
      }

      class org.un.sdgs.terratales.Location {
          - description : String
          - image : Image
          - name : String
          - place : String
          - x : int
          - y : int
          + Location()
          + getDescription()
          + getImage()
          + getName()
          + getPlace()
          + getX()
          + getY()
          + setDescription()
          + setImage()
          + setName()
          + setPlace()
          + setX()
          + setY()
          + toString()
      }

      class org.un.sdgs.terratales.LocationController {
          ~ descriptionLabel : Label
          ~ favoriteButton : Button
          ~ locationImage : ImageView
          ~ nameLabel : Label
          ~ nextButton : Button
          ~ placeLabel : Label
          ~ previousButton : Button
          ~ userLabel : Label
          {static} - loc : Location
          {static} - locIndex : int
          + changeLocation()
          + changeLocation()
          + onBackPress()
          + onClickNext()
          + onClickPrevious()
          + onFavoriteClick()
          + onFavoriteListPress()
          + onSignoutPress()
          - initialize()
          - setDropShadow()
      }

      class org.un.sdgs.terratales.LoginController {
          - password : PasswordField
          - prompt : Label
          - username : TextField
          + onLogInPress()
          + onSignUpPress()
          - initialize()
      }

      class org.un.sdgs.terratales.Main {
          {static} ~ window : Stage
          + changeScene()
          {static} + main()
          + start()
      }

      class org.un.sdgs.terratales.MapController {
          - locationsVbox : VBox
          - mapImage : ImageView
          - mapStack : AnchorPane
          - mapX : int
          - mapY : int
          - mapZoomLevel : int
          - userLabel : Label
          - createLocationButton()
          - initialize()
          - moveMap()
          - onMoveDownAction()
          - onMoveLeftAction()
          - onMoveRightAction()
          - onMoveUpAction()
          - onSignOutAction()
          - onViewFavoritesAction()
          - onViewLocationAction()
          - onZoomInAction()
          - onZoomOutAction()
      }

      class org.un.sdgs.terratales.SignupController {
          - password : PasswordField
          - prompt : Label
          - username : TextField
          + onLogInPress()
          + onSignUpPress()
          - checkIfUserExists()
          - initialize()
      }

      class org.un.sdgs.terratales.User {
          - favoritesList : ArrayList<Location>
          - password : String
          - username : String
          + User()
          + addFavorites()
          + getFavoritesList()
          + getPassword()
          + getUsername()
          + removeFavorites()
          + setPassword()
          + setUsername()
          + toString()
      }


      class org.un.sdgs.terratales.UserDatabase {
          {static} - instance : UserDatabase
          - userList : ArrayList<User>
          + UserDatabase()
          + getCurrentUser()
          {static} + getInstance()
          + getUserList()
          + load()
          + setCurrentUser()
      }

  org.un.sdgs.terratales.LandDatabase .up.|> org.un.sdgs.terratales.IDatabase
  org.un.sdgs.terratales.Main -up-|> javafx.application.Application
  org.un.sdgs.terratales.UserDatabase .up.|> org.un.sdgs.terratales.IDatabase
  org.un.sdgs.terratales.UserDatabase o-- org.un.sdgs.terratales.User : currentUser


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
